package parser

import (
	"slices"
	"strings"

	"github.com/creachadair/mds/mapset"
	"github.com/publicsuffix/list/tools/internal/domain"
)

// Exceptions are parts of the PSL that would fail current validation
// and stylistic requirements, but are exempted due to predating those
// rules.
//
// See the bottom of this file for the exceptions themselves.

// exemptFromContactInfo reports whether the block owned by entity is
// exempt from the requirement to have a contact email address.
func exemptFromContactInfo(entity string) bool {
	return slices.Contains(missingEmail, entity)
}

// exemptFromSorting reports whether the block owned by entity is
// exempt from the sorting requirement that normally applies in the
// private domains section.
func exemptFromSorting(entity string) bool {
	return slices.Contains(incorrectSort, entity)
}

// exemptFromTXT reports whether the given domain name is exempt from
// the requirement to have a _psl TXT record.
func exemptFromTXT(domain domain.Name) bool {
	s := domain.String()
	if missingTXT.Has(domain.String()) {
		return true
	}
	for _, suffix := range missingTXTAmazonSuffixes {
		if strings.HasSuffix(s, suffix) {
			return true
		}
	}
	return false
}

// missingEmail are source code blocks in the private domains section
// that are allowed to lack email contact information.
var missingEmail = []string{
	"611 blockchain domain name system",
	"c.la",
	"co.ca",
	"DynDNS.com",
	"Hashbang",
	"HostyHosting",
	"info.at",
	".KRD",
	"Michau Enterprises Limited",
	"Nicolaus Copernicus University in Torun - MSK TORMAN",
	"TASK geographical domains",
	"CoDNS B.V.",
	".pl domains (grandfathered)",
	"QA2",
}

// incorrectSort are entities in the private domains section that are
// allowed to be in the wrong sort order.
var incorrectSort = []string{
	"AAA workspace",
	"University of Banja Luka",
	"University of Bielsko-Biala regional domain",
	"No longer operated by CentralNic, these entries should be adopted and/or removed by current operators",
	"Africa.com Web Solutions Ltd",
	"iDOT Services Limited",
	"Radix FZC",
	"US REGISTRY LLC",
	"co.com Registry, LLC",
	"Roar Domains LLC",
	"BRS Media",
	"c.la",
	"Clever Cloud",
	"co.ca",
	"Co & Co",
	"i-registry s.r.o.",
	"CDN77.com",
	"Cloud DNS Ltd",
	"Daplie, Inc",
	"Datto, Inc.",
	"Bip",
	"bitbridge.net",
	"ddnss.de",
	"Definima",
	"DigitalOcean App Platform",
	"DigitalOcean Spaces",
	"DigitalPlat",
	"dnstrace.pro",
	"ECG Robotics, Inc",
	"Fedora",
	"Frusky MEDIA&PR",
	"RavPage",
	"CDDO",
	"GOV.UK Platform as a Service",
	"GOV.UK Pay",
	"Helio Networks",
	"Häkkinen.fi",
	"is-a.dev",
	"I-O DATA DEVICE, INC.",
	"KUROKU LTD",
	"Katholieke Universiteit Leuven",
	".KRD",
	"Lokalized",
	"May First - People Link",
	"mcpe.me",
	"NFSN, Inc.",
	"NFT.Storage",
	"No-IP.com",
	"NodeArt",
	"One.com",
	".pl domains (grandfathered)",
	"Pantheon Systems, Inc.",
	"PE Ulyanov Kirill Sergeevich",
	"Rad Web Hosting",
	"Raidboxes GmbH",
	"Redgate Software",
	"Redstar Consultants",
	"Russian Academy of Sciences",
	"QA2",
	"QCX",
	"QNAP System Inc",
	"Senseering GmbH",
	"Smallregistry by Promopixel SARL",
	"staticland",
	"Storebase",
	"Strapi",
	"Strategic System Consulting (eApps Hosting)",
	"Sony Interactive Entertainment LLC",
	"SourceLair PC",
	"SpaceKit",
	"SpeedPartner GmbH",
	"Spreadshop (sprd.net AG)",
	"Studenten Net Twente",
	"UNIVERSAL DOMAIN REGISTRY",
	".US",
	"VeryPositive SIA",
	"V.UA Domain Administrator",
}

// missingTXT are the domains that are exempt from the _psl TXT record
// requirement.
var missingTXT = mapset.New(
	"001www.com",
	"0emm.com",
	"4u.com",
	"64-b.it",
	"ac.ru",
	"accesscam.org",
	"adimo.co.uk",
	"ae.org",
	"africa.com",
	"akadns.net",
	"akamai-staging.net",
	"akamai.net",
	"akamaiedge-staging.net",
	"akamaiedge.net",
	"akamaihd-staging.net",
	"akamaihd.net",
	"akamaiorigin-staging.net",
	"akamaiorigin.net",
	"akamaized-staging.net",
	"akamaized.net",
	"al.eu.org",
	"ap.ngrok.io",
	"api.stdlib.com",
	"app.render.com",
	"appspot.com",
	"ar.com",
	"art.pl",
	"asso.eu.org",
	"at-band-camp.net",
	"at.eu.org",
	"ath.cx",
	"au.eu.org",
	"au.ngrok.io",
	"aus.basketball",
	"autocode.dev",
	"azure-api.net",
	"azure-mobile.net",
	"azureedge.net",
	"azurefd.net",
	"azurewebsites.net",
	"barrel-of-knowledge.info",
	"barrell-of-knowledge.info",
	"bci.dnstrace.pro",
	"be.eu.org",
	"beagleboard.io",
	"beta.bounty-full.com",
	"betainabox.com",
	"better-than.tv",
	"bg.eu.org",
	"biz.at",
	"biz.ua",
	"blob.core.windows.net",
	"blogdns.com",
	"blogdns.net",
	"blogdns.org",
	"blogsite.org",
	"blogsite.xyz",
	"blogspot.ae",
	"blogspot.al",
	"blogspot.am",
	"blogspot.ba",
	"blogspot.be",
	"blogspot.bg",
	"blogspot.bj",
	"blogspot.ca",
	"blogspot.cf",
	"blogspot.ch",
	"blogspot.cl",
	"blogspot.co.at",
	"blogspot.co.id",
	"blogspot.co.il",
	"blogspot.co.ke",
	"blogspot.co.nz",
	"blogspot.co.uk",
	"blogspot.co.za",
	"blogspot.com",
	"blogspot.com.ar",
	"blogspot.com.au",
	"blogspot.com.br",
	"blogspot.com.by",
	"blogspot.com.co",
	"blogspot.com.cy",
	"blogspot.com.ee",
	"blogspot.com.eg",
	"blogspot.com.es",
	"blogspot.com.mt",
	"blogspot.com.ng",
	"blogspot.com.tr",
	"campaign.gov.uk",
	"blogspot.com.uy",
	"blogspot.cv",
	"blogspot.cz",
	"blogspot.de",
	"blogspot.dk",
	"blogspot.fi",
	"blogspot.fr",
	"blogspot.gr",
	"blogspot.hk",
	"blogspot.hr",
	"blogspot.hu",
	"blogspot.ie",
	"blogspot.in",
	"blogspot.is",
	"blogspot.it",
	"blogspot.jp",
	"blogspot.kr",
	"blogspot.li",
	"blogspot.lt",
	"blogspot.lu",
	"blogspot.md",
	"blogspot.mk",
	"blogspot.mr",
	"blogspot.mx",
	"blogspot.my",
	"blogspot.nl",
	"blogspot.no",
	"blogspot.pe",
	"blogspot.pt",
	"blogspot.qa",
	"blogspot.re",
	"blogspot.ro",
	"blogspot.rs",
	"blogspot.ru",
	"blogspot.se",
	"blogspot.sg",
	"blogspot.si",
	"blogspot.sk",
	"blogspot.sn",
	"blogspot.tw",
	"blogspot.ug",
	"blogspot.vn",
	"bloxcms.com",
	"boldlygoingnowhere.org",
	"bookonline.app",
	"br.com",
	"broke-it.net",
	"buyshouses.net",
	"bzz.dapps.earth",
	"ca.eu.org",
	"camdvr.org",
	"casacam.net",
	"cd.eu.org",
	"cechire.com",
	"certmgr.org",
	"ch.eu.org",
	"cloud-fr1.unispace.io",
	"cloudapp.net",
	"cloudfront.net",
	"cloudfunctions.net",
	"cloudns.biz",
	"cloudns.in",
	"cloudns.info",
	"cloudns.us",
	"cn.com",
	"cn.eu.org",
	"co.business",
	"co.ca",
	"co.com",
	"co.cz",
	"co.education",
	"co.events",
	"co.financial",
	"co.krd",
	"co.network",
	"co.nl",
	"co.no",
	"co.pl",
	"co.place",
	"co.technology",
	"co.ua",
	"codeberg.page",
	"codespot.com",
	"com.de",
	"com.se",
	"crafting.xyz",
	"cryptonomic.net",
	"csx.cc",
	"curv.dev",
	"cy.eu.org",
	"cyon.link",
	"cyon.site",
	"cz.eu.org",
	"daplie.me",
	"dapps.earth",
	"ddnsfree.com",
	"ddnsgeek.com",
	"ddnslive.com",
	"ddnss.de",
	"de.com",
	"de.eu.org",
	"demo.datadetect.com",
	"diskstation.me",
	"dk.eu.org",
	"dnsalias.com",
	"dnsalias.net",
	"dnsalias.org",
	"dnsdojo.com",
	"dnsdojo.net",
	"dnsdojo.org",
	"dnshome.de",
	"does-it.net",
	"doesntexist.com",
	"doesntexist.org",
	"dontexist.com",
	"dontexist.net",
	"dontexist.org",
	"doomdns.com",
	"doomdns.org",
	"dreamhosters.com",
	"drud.us",
	"dscloud.biz",
	"dscloud.me",
	"dscloud.mobi",
	"dsmynas.com",
	"dsmynas.net",
	"dsmynas.org",
	"duckdns.org",
	"dvrdns.org",
	"dyn-o-saur.com",
	"dynalias.com",
	"dynalias.net",
	"dynalias.org",
	"dynathome.net",
	"dyndns-at-home.com",
	"dyndns-at-work.com",
	"dyndns-blog.com",
	"dyndns-free.com",
	"dyndns-home.com",
	"dyndns-ip.com",
	"dyndns-mail.com",
	"dyndns-office.com",
	"dyndns-pics.com",
	"dyndns-remote.com",
	"dyndns-server.com",
	"dyndns-web.com",
	"dyndns-wiki.com",
	"dyndns-work.com",
	"dyndns.biz",
	"dyndns.dappnode.io",
	"dyndns.info",
	"dyndns.org",
	"dyndns.tv",
	"dyndns.ws",
	"dynu.net",
	"dynv6.net",
	"e4.cz",
	"edgekey-staging.net",
	"edgekey.net",
	"edgesuite-staging.net",
	"edgesuite.net",
	"edu.eu.org",
	"edu.krd",
	"edu.ru",
	"edu.scot",
	"ee.eu.org",
	"endofinternet.net",
	"endofinternet.org",
	"endoftheinternet.org",
	"es.eu.org",
	"est-a-la-maison.com",
	"est-a-la-masion.com",
	"est-le-patron.com",
	"est-mon-blogueur.com",
	"eu.com",
	"eu.ngrok.io",
	"eu.org",
	"familyds.com",
	"familyds.net",
	"familyds.org",
	"fi.eu.org",
	"firebaseapp.com",
	"flap.id",
	"fly.dev",
	"for-better.biz",
	"for-more.biz",
	"for-our.info",
	"for-some.biz",
	"for-the.biz",
	"forgot.her.name",
	"forgot.his.name",
	"fr.eu.org",
	"free.hr",
	"freeddns.org",
	"from-ak.com",
	"from-al.com",
	"from-ar.com",
	"from-az.net",
	"from-ca.com",
	"from-co.net",
	"from-ct.com",
	"from-dc.com",
	"from-de.com",
	"from-fl.com",
	"from-ga.com",
	"from-hi.com",
	"from-ia.com",
	"from-id.com",
	"from-il.com",
	"from-in.com",
	"from-ks.com",
	"from-ky.com",
	"from-la.net",
	"from-ma.com",
	"from-md.com",
	"from-me.org",
	"from-mi.com",
	"from-mn.com",
	"from-mo.com",
	"from-ms.com",
	"from-mt.com",
	"from-nc.com",
	"from-nd.com",
	"from-ne.com",
	"from-nh.com",
	"from-nj.com",
	"from-nm.com",
	"from-nv.com",
	"from-ny.net",
	"from-oh.com",
	"from-ok.com",
	"from-or.com",
	"from-pa.com",
	"from-pr.com",
	"from-ri.com",
	"from-sc.com",
	"from-sd.com",
	"from-tn.com",
	"from-tx.com",
	"from-ut.com",
	"from-va.com",
	"from-vt.com",
	"from-wa.com",
	"from-wi.com",
	"from-wv.com",
	"from-wy.com",
	"ftpaccess.cc",
	"fuettertdasnetz.de",
	"game-host.org",
	"game-server.cc",
	"gb.net",
	"gda.pl",
	"gdansk.pl",
	"gdynia.pl",
	"getmyip.com",
	"gets-it.net",
	"giize.com",
	"github.io",
	"githubusercontent.com",
	"gleeze.com",
	"gliwice.pl",
	"go.dyndns.org",
	"googleapis.com",
	"googlecode.com",
	"gotdns.com",
	"gotdns.org",
	"gotpantheon.com",
	"gov.ru",
	"gr.com",
	"gr.eu.org",
	"groks-the.info",
	"groks-this.info",
	"gsj.bz",
	"günstigbestellen.de",
	"günstigliefern.de",
	"ham-radio-op.net",
	"hashbang.sh",
	"hepforge.org",
	"here-for-more.info",
	"herokuapp.com",
	"herokussl.com",
	"hk.com",
	"hk.org",
	"hobby-site.com",
	"hobby-site.org",
	"home.dyndns.org",
	"homedns.org",
	"homeftp.net",
	"homeftp.org",
	"homeip.net",
	"homelink.one",
	"homelinux.com",
	"homelinux.net",
	"homelinux.org",
	"homeunix.com",
	"homeunix.net",
	"homeunix.org",
	"hosting.ovh.net",
	"hr.eu.org",
	"hu.eu.org",
	"hu.net",
	"hzc.io",
	"häkkinen.fi",
	"i234.me",
	"iamallama.com",
	"id.firewalledreplit.co",
	"id.forgerock.io",
	"ie.eu.org",
	"iki.fi",
	"il.eu.org",
	"in-the-band.net",
	"in.eu.org",
	"in.net",
	"in.ngrok.io",
	"inc.hk",
	"ind.mom",
	"info.at",
	"int.eu.org",
	"int.ru",
	"is-a-anarchist.com",
	"is-a-blogger.com",
	"is-a-bookkeeper.com",
	"is-a-bruinsfan.org",
	"is-a-bulls-fan.com",
	"is-a-candidate.org",
	"is-a-caterer.com",
	"is-a-celticsfan.org",
	"is-a-chef.com",
	"is-a-chef.net",
	"is-a-chef.org",
	"is-a-conservative.com",
	"is-a-cpa.com",
	"is-a-cubicle-slave.com",
	"is-a-democrat.com",
	"is-a-designer.com",
	"is-a-doctor.com",
	"is-a-financialadvisor.com",
	"is-a-geek.com",
	"is-a-geek.net",
	"is-a-geek.org",
	"is-a-green.com",
	"is-a-guru.com",
	"is-a-hard-worker.com",
	"is-a-hunter.com",
	"is-a-knight.org",
	"is-a-landscaper.com",
	"is-a-lawyer.com",
	"is-a-liberal.com",
	"is-a-libertarian.com",
	"is-a-linux-user.org",
	"is-a-llama.com",
	"is-a-musician.com",
	"is-a-nascarfan.com",
	"is-a-nurse.com",
	"is-a-painter.com",
	"is-a-patsfan.org",
	"is-a-personaltrainer.com",
	"is-a-photographer.com",
	"is-a-player.com",
	"is-a-republican.com",
	"is-a-rockstar.com",
	"is-a-socialist.com",
	"is-a-soxfan.org",
	"is-a-student.com",
	"is-a-teacher.com",
	"is-a-techie.com",
	"is-a-therapist.com",
	"is-an-accountant.com",
	"is-an-actor.com",
	"is-an-actress.com",
	"is-an-anarchist.com",
	"is-an-artist.com",
	"is-an-engineer.com",
	"is-an-entertainer.com",
	"is-by.us",
	"is-certified.com",
	"is-found.org",
	"is-gone.com",
	"is-into-anime.com",
	"is-into-cars.com",
	"is-into-cartoons.com",
	"is-into-games.com",
	"is-leet.com",
	"is-lost.org",
	"is-not-certified.com",
	"is-saved.org",
	"is-slick.com",
	"is-uberleet.com",
	"is-very-bad.org",
	"is-very-evil.org",
	"is-very-good.org",
	"is-very-nice.org",
	"is-very-sweet.org",
	"is-with-theband.com",
	"is.eu.org",
	"isa-geek.com",
	"isa-geek.net",
	"isa-geek.org",
	"isa-hockeynut.com",
	"issmarterthanyou.com",
	"isteingeek.de",
	"istmein.de",
	"it.eu.org",
	"jp.eu.org",
	"jp.net",
	"jp.ngrok.io",
	"jpn.com",
	"js.wpenginepowered.com",
	"keymachine.de",
	"kicks-ass.net",
	"kicks-ass.org",
	"knightpoint.systems",
	"knowsitall.info",
	"kozow.com",
	"kr.eu.org",
	"krakow.pl",
	"land-4-sale.us",
	"lebtimnetz.de",
	"leitungsen.de",
	"lib.de.us",
	"likes-pie.com",
	"likescandy.com",
	"lk3.ru",
	"localhost.daplie.me",
	"loseyourip.com",
	"lt.eu.org",
	"ltd.hk",
	"lu.eu.org",
	"lv.eu.org",
	"me.eu.org",
	"med.pl",
	"memset.net",
	"merseine.nu",
	"messerli.app",
	"mex.com",
	"mil.ru",
	"mine.nu",
	"miniserver.com",
	"misconfused.org",
	"mk.eu.org",
	"moonscale.net",
	"mt.eu.org",
	"my.eu.org",
	"myasustor.com",
	"mycloud.by",
	"mydatto.com",
	"myddns.rocks",
	"mydrobo.com",
	"myds.me",
	"mypep.link",
	"mypets.ws",
	"myphotos.cc",
	"mywire.org",
	"neat-url.com",
	"net.eu.org",
	"netfy.app",
	"nfshost.com",
	"ng.eu.org",
	"nl.eu.org",
	"no.com",
	"no.eu.org",
	"now-dns.top",
	"nz.basketball",
	"nz.eu.org",
	"office-on-the.net",
	"on-rancher.cloud",
	"on-rio.io",
	"on-the-web.tv",
	"onfabrica.com",
	"onred.one",
	"onrender.com",
	"ooguy.com",
	"operaunite.com",
	"outsystemscloud.com",
	"ownprovider.com",
	"ox.rs",
	"pagespeedmobilizer.com",
	"paris.eu.org",
	"pl.eu.org",
	"platter-app.com",
	"podzone.net",
	"podzone.org",
	"poznan.pl",
	"pp.ua",
	"protonet.io",
	"pt.eu.org",
	"publishproxy.com",
	"q-a.eu.org",
	"qa2.com",
	"qbuser.com",
	"qc.com",
	"rackmaze.com",
	"rackmaze.net",
	"readmyblog.org",
	"realm.cz",
	"repl.run",
	"rhcloud.com",
	"ric.jelastic.vps-host.net",
	"ro.eu.org",
	"rss.my.id",
	"ru.com",
	"ru.eu.org",
	"sa.com",
	"sa.ngrok.io",
	"sandcats.io",
	"saves-the-whales.com",
	"scrapper-site.net",
	"scrapping.cc",
	"sdscloud.pl",
	"se.eu.org",
	"se.net",
	"selfip.biz",
	"selfip.com",
	"selfip.info",
	"selfip.net",
	"selfip.org",
	"sells-for-less.com",
	"sells-for-u.com",
	"sells-it.net",
	"sellsyourhome.org",
	"senseering.net",
	"servebbs.com",
	"servebbs.net",
	"servebbs.org",
	"serveftp.net",
	"serveftp.org",
	"servegame.org",
	"service.gov.uk",
	"servicebus.windows.net",
	"shacknet.nu",
	"shoparena.pl",
	"shopware.store",
	"si.eu.org",
	"simple-url.com",
	"sk.eu.org",
	"sopot.pl",
	"space-to-rent.com",
	"spacekit.io",
	"staging.onred.one",
	"static.observableusercontent.com",
	"stg.dev",
	"stuff-4-sale.org",
	"stuff-4-sale.us",
	"synology.me",
	"teaches-yoga.com",
	"test.ru",
	"theworkpc.com",
	"thruhere.net",
	"tickets.io",
	"toolforge.org",
	"townnews-staging.com",
	"tr.eu.org",
	"traeumtgerade.de",
	"trafficmanager.net",
	"translate.goog",
	"uk.com",
	"uk.eu.org",
	"uk.net",
	"us.com",
	"us.eu.org",
	"us.ngrok.io",
	"us.org",
	"user.party.eus",
	"uy.com",
	"vercel.app",
	"vercel.dev",
	"virtual-user.de",
	"vpnplus.to",
	"webhop.biz",
	"webhop.info",
	"webhop.net",
	"webhop.org",
	"webpaas.ovh.net",
	"webredirect.org",
	"withgoogle.com",
	"withyoutube.com",
	"wmcloud.org",
	"wmflabs.org",
	"worse-than.tv",
	"wpenginepowered.com",
	"wpmucdn.com",
	"writesthisblog.com",
	"wroc.pl",
	"xen.prgmr.com",
	"yolasite.com",
	"za.bz",
	"za.com",
	"za.net",
	"za.org",
	"zakopane.pl",
	"zapto.xyz",
	"биз.рус",
	"ком.рус",
	"крым.рус",
	"мир.рус",
	"мск.рус",
	"орг.рус",
	"самара.рус",
	"сочи.рус",
	"спб.рус",
	"я.рус",

	// DNS server down, 2024-09-17
	"amscompute.com",
	"cloud.jelastic.open.tim.it",
	"faststacks.net",
	"firm.ng",
	"hs.run",
	"hs.zone",
	"hu.com",
	"jelastic.regruhosting.ru",
	"jelastic.tsukaeru.net",
	"kilatiron.com",
	"kr.com",
	"krellian.net",
	"lon.wafaicloud.com",
	"mc.eu.org",
	"mycd.eu",
	"n4t.co",
	"upaas.kazteleport.kz",
	"wellbeingzone.co.uk",
	"ybo.faith",
	"ybo.party",
	"ybo.science",
	"ybo.trade",

	// SERVFAIL, 2024-09-17
	"blogspot.td",
	"ddns5.com",
	"dyn53.io",
	"forte.id",
	"ktistory.com",
	"mo-siemens.io",
	"on-acorn.io",
	"s5y.io",
	"scrysec.com",
	"sensiosite.cloud",
	"shiftedit.io",
	"ybo.review",
)

// missingTXTAmazonSuffixes are Amazon domains that are exempt from
// the _psl TXT requirement, due to managing their submissions through
// a separate high-volume process.
var missingTXTAmazonSuffixes = []string{
	".amazonaws.com",
	".amazonaws.com.cn",
	".amazoncognito.com",
}
