name: validate

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: run validations
        run: |
          cd tools
          go run ./psltool validate ../public_suffix_list.dat
